import type { StandardsPayload } from "@/lib/standards/types";

export const noRestockStandardsSeed: StandardsPayload = {
  source: "2025 historical import derived from All Data + Daily Operations Stats + UserLS",
  methodology: [
    "Uses letdowns + putaways only. Restocks are excluded.",
    "Standards are based on median active day per role or team area.",
    "Hourly estimates use 2025 total hours divided by active workdays. No 8-hour normalization is used.",
    "Receiving is intentionally excluded from this standards set because it is not comparable once the focus is narrowed to letdown + putaway work.",
  ],
  updatedAt: "2026-04-06",
  teamAreas: [
    {
      scopeType: "team_area",
      scopeName: "Cooler",
      activeDays: 976,
      distinctPeople: 16,
      dailyPlatesStandard: 100,
      dailyPiecesStandard: 1720.5,
      dailyPiecesPerPlateStandard: 17.385,
      estimatedHoursPerDayFrom2025Hours: 9.347,
      platesPerHourEstimated: 10.698,
      piecesPerHourEstimated: 184.065,
      status: "ready",
      notes: "Use for full-team Cooler tracking. Individual expectations should still use ClrDairy, ClrMeat, or Produce role standards.",
    },
    {
      scopeType: "team_area",
      scopeName: "Dry",
      activeDays: 847,
      distinctPeople: 15,
      dailyPlatesStandard: 100,
      dailyPiecesStandard: 1667,
      dailyPiecesPerPlateStandard: 19.784,
      estimatedHoursPerDayFrom2025Hours: 9.449,
      platesPerHourEstimated: 10.583,
      piecesPerHourEstimated: 176.413,
      status: "ready",
      notes: "Dry team area standard combines DryFlr, DryMix, and DryPIR for high-level team monitoring.",
    },
    {
      scopeType: "team_area",
      scopeName: "Freezer",
      activeDays: 1039,
      distinctPeople: 10,
      dailyPlatesStandard: 104,
      dailyPiecesStandard: 1827,
      dailyPiecesPerPlateStandard: 17.827,
      estimatedHoursPerDayFrom2025Hours: 8.638,
      platesPerHourEstimated: 12.04,
      piecesPerHourEstimated: 211.504,
      status: "ready",
      notes: "Freezer team area standard combines FrzLet, FrzMix, FrzPut, and FrzPIR for high-level team monitoring.",
    },
  ],
  roles: [
    {
      scopeType: "role",
      scopeName: "ClrDairy",
      activeDays: 337,
      distinctPeople: 12,
      dailyPlatesStandard: 86,
      dailyPiecesStandard: 1890,
      dailyPiecesPerPlateStandard: 20.78,
      estimatedHoursPerDayFrom2025Hours: 9.136,
      platesPerHourEstimated: 9.413,
      piecesPerHourEstimated: 206.864,
      status: "ready",
      notes: "Use for individual dairy/cooler operators mapped to ClrDairy.",
    },
    {
      scopeType: "role",
      scopeName: "ClrMeat",
      activeDays: 271,
      distinctPeople: 10,
      dailyPlatesStandard: 107,
      dailyPiecesStandard: 1547,
      dailyPiecesPerPlateStandard: 14.474,
      estimatedHoursPerDayFrom2025Hours: 9.734,
      platesPerHourEstimated: 10.992,
      piecesPerHourEstimated: 158.925,
      status: "ready",
      notes: "Use for individual meat/cooler operators mapped to ClrMeat.",
    },
    {
      scopeType: "role",
      scopeName: "Produce",
      activeDays: 368,
      distinctPeople: 8,
      dailyPlatesStandard: 104.5,
      dailyPiecesStandard: 1878.5,
      dailyPiecesPerPlateStandard: 17.618,
      estimatedHoursPerDayFrom2025Hours: 9.347,
      platesPerHourEstimated: 11.18,
      piecesPerHourEstimated: 200.969,
      status: "ready",
      notes: "Use for produce cooler operators.",
    },
    {
      scopeType: "role",
      scopeName: "DryFlr",
      activeDays: 316,
      distinctPeople: 13,
      dailyPlatesStandard: 102,
      dailyPiecesStandard: 2389.5,
      dailyPiecesPerPlateStandard: 24.081,
      estimatedHoursPerDayFrom2025Hours: 9.449,
      platesPerHourEstimated: 10.794,
      piecesPerHourEstimated: 252.873,
      status: "ready",
      notes: "Use for DryFlr individuals.",
    },
    {
      scopeType: "role",
      scopeName: "DryMix",
      activeDays: 274,
      distinctPeople: 9,
      dailyPlatesStandard: 104,
      dailyPiecesStandard: 2373.5,
      dailyPiecesPerPlateStandard: 22.664,
      estimatedHoursPerDayFrom2025Hours: 9.347,
      platesPerHourEstimated: 11.126,
      piecesPerHourEstimated: 253.926,
      status: "ready",
      notes: "Use for DryMix individuals. Similar hourly output to DryFlr but still keep separate roles.",
    },
    {
      scopeType: "role",
      scopeName: "DryPIR",
      activeDays: 257,
      distinctPeople: 8,
      dailyPlatesStandard: 91,
      dailyPiecesStandard: 864,
      dailyPiecesPerPlateStandard: 8.916,
      estimatedHoursPerDayFrom2025Hours: 8.638,
      platesPerHourEstimated: 10.535,
      piecesPerHourEstimated: 100.022,
      status: "provisional",
      notes: "Keep separate from FrzPIR. Lower-density work profile than the main Dry roles.",
    },
    {
      scopeType: "role",
      scopeName: "FrzLet",
      activeDays: 282,
      distinctPeople: 6,
      dailyPlatesStandard: 84,
      dailyPiecesStandard: 2547.5,
      dailyPiecesPerPlateStandard: 31.479,
      estimatedHoursPerDayFrom2025Hours: 7.989,
      platesPerHourEstimated: 10.515,
      piecesPerHourEstimated: 318.891,
      status: "ready",
      notes: "Very dense role. Lower plates than FrzPut but much heavier per plate.",
    },
    {
      scopeType: "role",
      scopeName: "FrzMix",
      activeDays: 259,
      distinctPeople: 5,
      dailyPlatesStandard: 112,
      dailyPiecesStandard: 1587,
      dailyPiecesPerPlateStandard: 14.355,
      estimatedHoursPerDayFrom2025Hours: 8.059,
      platesPerHourEstimated: 13.898,
      piecesPerHourEstimated: 196.929,
      status: "ready",
      notes: "Very stable between estimated-hours and assumed-8-hour views.",
    },
    {
      scopeType: "role",
      scopeName: "FrzPIR",
      activeDays: 259,
      distinctPeople: 5,
      dailyPlatesStandard: 101,
      dailyPiecesStandard: 810,
      dailyPiecesPerPlateStandard: 8.708,
      estimatedHoursPerDayFrom2025Hours: 10.407,
      platesPerHourEstimated: 9.705,
      piecesPerHourEstimated: 77.832,
      status: "provisional",
      notes: "Keep separate from DryPIR. Hourly spread between estimated-hours and 8-hour views is larger here.",
    },
    {
      scopeType: "role",
      scopeName: "FrzPut",
      activeDays: 239,
      distinctPeople: 5,
      dailyPlatesStandard: 137,
      dailyPiecesStandard: 3625,
      dailyPiecesPerPlateStandard: 28.863,
      estimatedHoursPerDayFrom2025Hours: 9.399,
      platesPerHourEstimated: 14.577,
      piecesPerHourEstimated: 385.699,
      status: "ready",
      notes: "Strongest freezer role by both plates/hour and pieces/hour in this standards set.",
    },
  ],
};
